apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    tier: front-end
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      tier: front-end
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        tier: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx


